# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.
# The "legacy_isotime" function has been provided for backwards compatability, but we recommend switching to the timestamp and formatdate functions.

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "proxmox" "ubuntu" {
  boot_command = [
    "<esc>c", 
    "linux /casper/vmlinuz --- autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/' ", 
    "<enter><wait5>", "initrd /casper/initrd<enter><wait10><wait10><wait10>", 
    "boot<enter>"]
  boot_wait    = "10s"
  cores        = "2"
  cpu_type     = "host"
  disks {
    disk_size         = "24G"
    storage_pool      = "local-lvm"
    storage_pool_type = "lvm"
    type              = "scsi"
  }
  http_directory           = "config"
  insecure_skip_tls_verify = true
  iso_file                 = "local:iso/ubuntu-22.04.1-live-server-amd64.iso"
  memory                   = "2048"
  network_adapters {
    bridge = "vmbr0"
  }
  node                 = "${var.node}"
  proxmox_url          = "${var.proxmox_url}"
  qemu_agent           = true
  ssh_password         = "ubuntu"
  ssh_timeout          = "30m"
  ssh_username         = "ubuntu"
  template_description = "Ubuntu 22.04, generated on ${legacy_isotime("2006-01-02T15:04:05Z")}"
  template_name        = "ubuntu22.04"
  token                = "${var.pve_token}"
  unmount_iso          = true
  username             = "${var.pve_username}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.proxmox.ubuntu"]

  provisioner "shell" {
    # This runs with all sources.
    inline = ["echo 'rubber ducky'> ducky.txt"]
  }
}
